title: Kapesní průvodce počítačových technologií
author: Martin Havelka 
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: encyklopedie.tex

bibtex_bibfiles:
  - references.bib

repository:
  url: https://github.com/mhavelka77/encyklopedie_technologie  